# Generated by Django 4.0.5 on 2022-06-09 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('idnotes', models.AutoField(primary_key=True, serialize=False)),
                ('note_1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('note_2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('note_3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('note_4', models.DecimalField(decimal_places=2, max_digits=4)),
                ('note_5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('average', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('activate', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=250)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.roles')),
                ('user_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.users')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('idestate', models.AutoField(primary_key=True, serialize=False)),
                ('name_estate', models.CharField(max_length=50)),
                ('notes_idnotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.notes')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('idcourses', models.AutoField(primary_key=True, serialize=False)),
                ('name_course', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=300)),
                ('price_course', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.CharField(max_length=500)),
                ('users_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.users')),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('idcertificate', models.AutoField(primary_key=True, serialize=False)),
                ('name_certificate', models.CharField(max_length=250)),
                ('courses_idcourses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.courses')),
                ('user_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.users')),
            ],
        ),
        migrations.CreateModel(
            name='Assitens',
            fields=[
                ('idassistens', models.AutoField(primary_key=True, serialize=False)),
                ('abstens', models.CharField(max_length=100)),
                ('delay', models.CharField(max_length=100)),
                ('courses_idcourses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituto.courses')),
            ],
        ),
    ]
